import type { CommandType } from './command-contract.js';

// Single classification of every GameCommand type. QUERY never changes game
// state, so re-executing it is harmless; MUTATION may only reach an Agent
// that keeps a durable execution journal (dedup by commandId). The Record
// type makes a new command type without a kind a compile error.
export type CommandKind = 'QUERY' | 'MUTATION';
export const COMMAND_KINDS: Readonly<Record<CommandType, CommandKind>> = {
  BRIDGE_PING: 'QUERY',
  CHARACTER_INVENTORY_QUERY: 'QUERY',
  CHARACTER_INVENTORY_REMOVE_ITEM: 'MUTATION',
  CHARACTER_ITEM_GIVE: 'MUTATION',
  CHARACTER_PROPERTIES_QUERY: 'QUERY',
  CHARACTER_PROPERTY_GRANT: 'MUTATION',
  CHARACTER_PROPERTY_REVOKE: 'MUTATION',
  CHARACTER_HOLDS_QUERY: 'QUERY',
  CHARACTER_HOLD_GRANT: 'MUTATION',
  CHARACTER_HOLD_REVOKE: 'MUTATION',
  CHARACTER_HORSES_QUERY: 'QUERY',
  CHARACTER_HORSE_GIVE: 'MUTATION',
  CHARACTER_HORSE_REVOKE: 'MUTATION',
  CHARACTER_TITLE_GIVE: 'MUTATION',
  CHARACTER_SPELL_GIVE: 'MUTATION',
  CHARACTER_FACTIONS_QUERY: 'QUERY',
  CHARACTER_FACTION_ADD: 'MUTATION',
  CHARACTER_FACTION_REMOVE: 'MUTATION',
  PLAYER_BAN: 'MUTATION',
  PLAYER_UNBAN: 'MUTATION',
  PLAYER_GOD_MODE_SET: 'MUTATION',
  STAFF_NOCLIP_SET: 'MUTATION',
  STAFF_INVISIBILITY_SET: 'MUTATION',
  ANNOUNCEMENT_SEND: 'MUTATION',
  STAFF_TELEPORT_TO_PLAYER: 'MUTATION',
  PLAYER_TELEPORT_TO_STAFF: 'MUTATION',
  WORLD_STATE_QUERY: 'QUERY',
  WORLD_TIME_SET: 'MUTATION',
  WORLD_WEATHER_SET: 'MUTATION',
  WORLD_ENTITY_SPAWN: 'MUTATION',
  CHARACTER_PROFILE_QUERY: 'QUERY',
  CHARACTER_SKILLS_QUERY: 'QUERY',
};
export const isMutation = (type: CommandType) =>
  COMMAND_KINDS[type] === 'MUTATION';
