import type { RoleName } from '../rbac/roles.js';
import type { Actor } from '../actors/actor.contracts.js';

export enum AuditAction {
  PLAYER_GROUP_CREATED = 'PLAYER_GROUP_CREATED',
  PLAYER_GROUP_INVITED = 'PLAYER_GROUP_INVITED',
  PLAYER_GROUP_INVITE_ACCEPTED = 'PLAYER_GROUP_INVITE_ACCEPTED',
  PLAYER_GROUP_INVITE_DECLINED = 'PLAYER_GROUP_INVITE_DECLINED',
  PLAYER_GROUP_MEMBER_LEFT = 'PLAYER_GROUP_MEMBER_LEFT',
  PLAYER_GROUP_MEMBER_KICKED = 'PLAYER_GROUP_MEMBER_KICKED',
  PLAYER_GROUP_DISBANDED = 'PLAYER_GROUP_DISBANDED',
  PROFESSION_SELECTED = 'PROFESSION_SELECTED',
  PROFESSION_EXPERIENCE_GRANTED = 'PROFESSION_EXPERIENCE_GRANTED',
  PLAYER_CHARACTER_LINK_REQUESTED = 'PLAYER_CHARACTER_LINK_REQUESTED',
  PLAYER_CHARACTER_LINK_VERIFIED = 'PLAYER_CHARACTER_LINK_VERIFIED',
  PLAYER_CHARACTER_LINK_REVOKED = 'PLAYER_CHARACTER_LINK_REVOKED',
  SERVER_START_REQUESTED = 'SERVER_START_REQUESTED',
  SERVER_PAUSE_REQUESTED = 'SERVER_PAUSE_REQUESTED',
  SERVER_RESTART_REQUESTED = 'SERVER_RESTART_REQUESTED',
  VIP_OFFER_CREATED = 'VIP_OFFER_CREATED',
  VIP_OFFER_UPDATED = 'VIP_OFFER_UPDATED',
  VIP_OFFER_ACTIVATED = 'VIP_OFFER_ACTIVATED',
  VIP_OFFER_DEACTIVATED = 'VIP_OFFER_DEACTIVATED',
  WORLD_TIME_SET_REQUESTED = 'WORLD_TIME_SET_REQUESTED',
  WORLD_WEATHER_SET_REQUESTED = 'WORLD_WEATHER_SET_REQUESTED',
  WORLD_ENTITY_SPAWN_REQUESTED = 'WORLD_ENTITY_SPAWN_REQUESTED',
  PLAYER_BAN_REQUESTED = 'PLAYER_BAN_REQUESTED',
  PLAYER_UNBAN_REQUESTED = 'PLAYER_UNBAN_REQUESTED',
  PLAYER_GOD_MODE_SET_REQUESTED = 'PLAYER_GOD_MODE_SET_REQUESTED',
  STAFF_NOCLIP_SET_REQUESTED = 'STAFF_NOCLIP_SET_REQUESTED',
  STAFF_INVISIBILITY_SET_REQUESTED = 'STAFF_INVISIBILITY_SET_REQUESTED',
  ANNOUNCEMENT_SEND_REQUESTED = 'ANNOUNCEMENT_SEND_REQUESTED',
  STAFF_TELEPORT_TO_PLAYER_REQUESTED = 'STAFF_TELEPORT_TO_PLAYER_REQUESTED',
  PLAYER_TELEPORT_TO_STAFF_REQUESTED = 'PLAYER_TELEPORT_TO_STAFF_REQUESTED',

  CHARACTER_INVENTORY_ITEM_REMOVE_REQUESTED = 'CHARACTER_INVENTORY_ITEM_REMOVE_REQUESTED',
  CHARACTER_ITEM_GIVE_REQUESTED = 'CHARACTER_ITEM_GIVE_REQUESTED',
  CHARACTER_PROPERTY_GRANT_REQUESTED = 'CHARACTER_PROPERTY_GRANT_REQUESTED',
  CHARACTER_PROPERTY_REVOKE_REQUESTED = 'CHARACTER_PROPERTY_REVOKE_REQUESTED',
  CHARACTER_HOLD_GRANT_REQUESTED = 'CHARACTER_HOLD_GRANT_REQUESTED',
  CHARACTER_HOLD_REVOKE_REQUESTED = 'CHARACTER_HOLD_REVOKE_REQUESTED',
  CHARACTER_HORSE_GIVE_REQUESTED = 'CHARACTER_HORSE_GIVE_REQUESTED',
  CHARACTER_HORSE_REVOKE_REQUESTED = 'CHARACTER_HORSE_REVOKE_REQUESTED',
  CHARACTER_TITLE_GIVE_REQUESTED = 'CHARACTER_TITLE_GIVE_REQUESTED',
  CHARACTER_SPELL_GIVE_REQUESTED = 'CHARACTER_SPELL_GIVE_REQUESTED',
  CHARACTER_FACTION_ADD_REQUESTED = 'CHARACTER_FACTION_ADD_REQUESTED',
  CHARACTER_FACTION_REMOVE_REQUESTED = 'CHARACTER_FACTION_REMOVE_REQUESTED',

  STAFF_CREATE = 'STAFF_CREATE',
  STAFF_UPDATE = 'STAFF_UPDATE',
  STAFF_ROLE_CHANGE = 'STAFF_ROLE_CHANGE',
  STAFF_STATUS_CHANGE = 'STAFF_STATUS_CHANGE',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  COORDINATOR_BOOTSTRAP = 'COORDINATOR_BOOTSTRAP',
}
export enum AuditOutcome {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}
export enum AuditResource {
  PLAYER_GROUP = 'PLAYER_GROUP',
  CHARACTER_PROFESSION = 'CHARACTER_PROFESSION',
  PLAYER_CHARACTER = 'PLAYER_CHARACTER',
  SERVER_CONTROL = 'SERVER_CONTROL',
  VIP_OFFER = 'VIP_OFFER',
  WORLD = 'WORLD',
  MODERATION = 'MODERATION',
  CHARACTER = 'CHARACTER',
  STAFF_USER = 'STAFF_USER',
  STAFF_SESSION = 'STAFF_SESSION',
}
export interface AuditActor {
  id: string;
  username: string;
  displayName: string;
  roleName: RoleName;
}
export type AuditMetadata = Record<string, unknown>;
// Staff snapshot without a type (existing callers) is interpreted as STAFF.
export type AuditEventActor = AuditActor | Actor;
export interface AuditEvent {
  actor?: AuditEventActor;
  action: AuditAction;
  resourceType?: AuditResource;
  resourceId?: string;
  metadata?: AuditMetadata;
  statusCode?: number;
}
export interface AuditResult<T> {
  value: T;
  actor?: AuditEventActor;
  resourceId?: string;
  metadata?: AuditMetadata;
}
