import { Permission } from './permissions.js';
import { RoleName } from './roles.js';

// Explicit grants: DEV is independent of the administrative roles.
export const ROLE_PERMISSIONS: Readonly<
  Record<RoleName, readonly Permission[]>
> = {
  [RoleName.COORDINATOR]: [
    Permission.WORLD_READ,
    Permission.WORLD_TIME_WRITE,
    Permission.WORLD_WEATHER_WRITE,
    Permission.WORLD_ENTITY_SPAWN,

    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.STAFF_READ,
    Permission.STAFF_WRITE,
    Permission.VIP_STORE_WRITE,
    Permission.VIP_STORE_READ,
    Permission.SERVER_START,
    Permission.SERVER_PAUSE,
    Permission.SERVER_RESTART,
    Permission.CHARACTER_INVENTORY_READ,
    Permission.CHARACTER_INVENTORY_WRITE,
    Permission.CHARACTER_PROPERTY_READ,
    Permission.CHARACTER_PROPERTY_WRITE,
    Permission.CHARACTER_HOLD_READ,
    Permission.CHARACTER_HOLD_WRITE,
    Permission.CHARACTER_HORSE_READ,
    Permission.CHARACTER_HORSE_WRITE,
    Permission.CHARACTER_ITEM_GIVE,
    Permission.CHARACTER_HORSE_GIVE,
    Permission.CHARACTER_TITLE_GIVE,
    Permission.CHARACTER_SPELL_GIVE,
    Permission.FACTION_READ,
    Permission.FACTION_WRITE,
    Permission.PLAYER_BAN,
    Permission.PLAYER_UNBAN,
    Permission.PLAYER_GOD_MODE,
    Permission.STAFF_NOCLIP,
    Permission.STAFF_INVISIBILITY,
    Permission.AUDIT_READ,
    Permission.ANNOUNCEMENT_SEND,
    Permission.STAFF_TELEPORT_TO_PLAYER,
    Permission.PLAYER_TELEPORT_TO_STAFF,
    Permission.GAME_AGENT_CREDENTIAL_MANAGE,
  ],
  [RoleName.GENERAL_CHIEF]: [
    Permission.WORLD_READ,
    Permission.WORLD_TIME_WRITE,
    Permission.WORLD_WEATHER_WRITE,
    Permission.WORLD_ENTITY_SPAWN,

    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.CHARACTER_INVENTORY_READ,
    Permission.CHARACTER_INVENTORY_WRITE,
    Permission.CHARACTER_PROPERTY_READ,
    Permission.CHARACTER_PROPERTY_WRITE,
    Permission.CHARACTER_HOLD_READ,
    Permission.CHARACTER_HOLD_WRITE,
    Permission.CHARACTER_HORSE_READ,
    Permission.CHARACTER_HORSE_WRITE,
    Permission.CHARACTER_ITEM_GIVE,
    Permission.CHARACTER_HORSE_GIVE,
    Permission.CHARACTER_TITLE_GIVE,
    Permission.CHARACTER_SPELL_GIVE,
    Permission.FACTION_READ,
    Permission.FACTION_WRITE,
    Permission.PLAYER_BAN,
    Permission.PLAYER_UNBAN,
    Permission.PLAYER_GOD_MODE,
    Permission.STAFF_NOCLIP,
    Permission.STAFF_INVISIBILITY,
    Permission.AUDIT_READ,
    Permission.ANNOUNCEMENT_SEND,
    Permission.STAFF_TELEPORT_TO_PLAYER,
    Permission.PLAYER_TELEPORT_TO_STAFF,
  ],
  [RoleName.ADMIN]: [
    Permission.WORLD_READ,

    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.PLAYER_BAN,
    Permission.PLAYER_UNBAN,
    Permission.PLAYER_GOD_MODE,
    Permission.STAFF_NOCLIP,
    Permission.STAFF_INVISIBILITY,
    Permission.AUDIT_READ,
    Permission.ANNOUNCEMENT_SEND,
    Permission.STAFF_TELEPORT_TO_PLAYER,
    Permission.PLAYER_TELEPORT_TO_STAFF,
  ],
  [RoleName.MODERATOR]: [
    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.STAFF_NOCLIP,
    Permission.STAFF_INVISIBILITY,
    Permission.AUDIT_READ,
    Permission.ANNOUNCEMENT_SEND,
    Permission.STAFF_TELEPORT_TO_PLAYER,
    Permission.PLAYER_TELEPORT_TO_STAFF,
  ],
  [RoleName.SUPPORT]: [
    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.PLAYER_TELEPORT_TO_STAFF,
  ],
  [RoleName.DEV]: [
    Permission.DASHBOARD_READ,
    Permission.GAME_BRIDGE_READ,
    Permission.SERVER_START,
    Permission.SERVER_PAUSE,
    Permission.SERVER_RESTART,
    Permission.GAME_AGENT_CREDENTIAL_MANAGE,
  ],
};
